app_covid/app_covid/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import  include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500
from covid import views as key
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('covid.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = key.Error404View.as_view()
handler500 = key.Error500View.as_error_view()

app_covid/covid/urls.py
#Django
from django.urls import path
from covid import views as key

urlpatterns = [
 #MENU
    path('', key.Dashboard_view.as_view(), name="dashboard" ),
    path('menu/', key.MenuListView.as_view(), name="menu_listar") ,
    path('menu/acceso/', key.Menu_AccesoListView.as_view(), name="menuAcceso_listar") ,
    path('menu/acceso/editar/<int:pk>', key.Menu_AccesoUpdateView.as_view(), name="menuAcceso_editar") ,
    path('menu/crear/', key.MenuCreateView.as_view(), name="menu_crear") ,
    path('menu/editar/<int:pk>', key.MenuUpdateView.as_view(), name="menu_editar") ,
    path('menu/Eliminar/<int:pk>', key.MenuDeleteView.as_view(), name="menu_eliminar") ,
    path('menu/Detalle/<int:pk>', key.MenuDetailView.as_view(), name="menu_detalle") ,

    path('grupo/', key.GrupoListView.as_view(), name="grupo_listar") ,
    path('grupo/crear/', key.GrupoCreateView.as_view(), name="grupo_crear") ,
    path('grupo/editar/<int:pk>', key.GrupoUpdateView.as_view(), name="grupo_editar") ,
    path('grupo/Eliminar/<int:pk>', key.GrupoDeleteView.as_view(), name="grupo_eliminar") ,
    path('grupo/Detalle/<int:pk>', key.GrupoDetailView.as_view(), name="grupo_detalle") ,


    path('usuario/', key.UsuarioListView.as_view(), name="usuario_listar") ,
    path('usuario/crear/', key.UsuarioCreateView.as_view(), name="usuario_crear") ,
    path('usuario/editar/<int:pk>', key.UsuarioUpdateView.as_view(), name="usuario_editar") ,
    path('usuario/Eliminar/<int:pk>', key.UsuarioDeleteView.as_view(), name="usuario_eliminar") ,
    path('usuario/Detalle/<int:pk>', key.UsuarioDetailView.as_view(), name="usuario_detalle") ,


    path('MyPerfil/', key.PerfilUpdateView.as_view(), name="perfilUsuario") ,
    path('MyPerfil/change-password/', key.PasswordChangeView.as_view(),name="CambiarContraseña" ),
    
    
    path('especialidad/', key.EspecialidadMedicoListView.as_view(), name="especialidadMedico_listar") ,
    path('especialidad/crear/', key.EspecialidadMedicoCreateView.as_view(), name="especialidadMedico_crear") ,
    path('especialidad/editar/<int:pk>', key.EspecialidadMedicoUpdateView.as_view(), name="especialidadMedico_editar") ,
    path('especialidad/Eliminar/<int:pk>', key.EspecialidadMedicoDeleteView.as_view(), name="especialidadMedico_eliminar") ,
    path('especialidad/Detalle/<int:pk>', key.EspecialidadMedicoDetailView.as_view(), name="especialidadMedico_detalle") ,
  
  
    path('medico/', key.MedicoListView.as_view(), name="medico_listar") ,
    path('medico/crear/', key.MedicoCreateView.as_view(), name="medico_crear") ,
    path('medico/editar/<int:pk>', key.MedicoUpdateView.as_view(), name="medico_editar") ,
    path('medico/Eliminar/<int:pk>', key.MedicoDeleteView.as_view(), name="medico_eliminar") ,
    path('medico/Detalle/<int:pk>', key.MedicoDetailView.as_view(), name="medico_detalle") ,
    
    path('paciente/', key.PacienteListView.as_view(), name="paciente_listar") ,
    path('paciente/crear/', key.PacienteCreateView.as_view(), name="paciente_crear") ,
    path('paciente/editar/<int:pk>', key.PacienteUpdateView.as_view(), name="paciente_editar") ,
    path('paciente/Eliminar/<int:pk>', key.PacienteDeleteView.as_view(), name="paciente_eliminar") ,
    path('paciente/Detalle/<int:pk>', key.PacienteDetailView.as_view(), name="paciente_detalle") ,
    
    
    path('report/', key.ReportView.as_view(),name='reporte'),
    
    
    path('rayx/',key.RayxListView.as_view(),name="rayx_listar"),
    path('rayx/crear/',key.RayxCreateView.as_view(),name="rayx_crear"),
    path('rayx/editar/<int:pk>',key.RayxUpdateView.as_view(),name="rayx_editar"),
    path('rayx/Eliminar/<int:pk>',key.RayxDeleteView.as_view(),name="rayx_eliminar"),
    path('rayx/Detalle/<int:pk>',key.RayxDetailView.as_view(),name="rayx_detalle"),
    path('rayx/DetallePac/<int:pk>',key.RayxPacDetailView.as_view(),name="rayx_detalle_paciente"),
    
    path('myresultado/',key.MyresultListView.as_view(),name="myresultado_listar"),
    path('myresultado/Detalle/<int:pk>',key.MyresultRayxDetailView.as_view(),name="myresultado_detalle"), 
     
    path('vacuna/', key.VacunaListView.as_view(), name="vacuna_listar") ,
    path('vacuna/crear/', key.VacunaCreateView.as_view(), name="vacuna_crear") ,
    path('vacuna/editar/<int:pk>', key.VacunaUpdateView.as_view(), name="vacuna_editar") ,
    path('vacuna/Eliminar/<int:pk>', key.VacunaDeleteView.as_view(), name="vacuna_eliminar") ,
    path('vacuna/Detalle/<int:pk>', key.VacunaDetailView.as_view(), name="vacuna_detalle") ,
  
  
]

app_covid/covid/models.py
#DJANGO

from django.db import models
from django.contrib.auth.models import Group, AbstractUser, Permission
from django.conf import settings


import os
from django.db.models.signals import pre_delete, post_delete, pre_save
from django.dispatch import receiver


#auditoria - crum django
from crum import get_current_user

from datetime import date, datetime, timezone

#MODELO BASE - CLASE ABSTRACTA
class ModeloBase(models.Model):
    class Meta:
        """Meta definition for ModeloBase."""
        abstract = True


    """Model definition for ModeloBase."""
    fecha_creacion = models.DateTimeField(verbose_name='Fecha creación',auto_now_add=True)
    usuario_creacion = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuario Creación', related_name='+', blank=True, null=True,on_delete=models.PROTECT, editable=False)
    usuario_modificacion = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación', related_name='+', blank=True, null=True,on_delete=models.PROTECT , editable=False)
    fecha_modificacion = models.DateTimeField(verbose_name='Fecha Modificación', auto_now=True)
    estado_registro = models.BooleanField(verbose_name="Estado del registro",default=True)
    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.usuario_creacion = user
        self.usuario_modificacion = user
        super(ModeloBase, self).save(*args, **kwargs)




class User(AbstractUser,ModeloBase):
    cedula=models.CharField(max_length=10, verbose_name='Cédula', unique = True)
    tipo_genero = (('M', 'Masculino'), ('F', 'Femenino'))
    genero = models.CharField('Género', choices=tipo_genero, default='M', max_length=1)
    
    def get_full_name(self):
        """Unicode representation of Analisis_Radiografico."""
        return '{} {}'.format(self.last_name,self.first_name)

#Especialidad
class EspecialidadMedico(ModeloBase):
    descripcion = models.CharField("Especialidad", max_length=200 , unique=True)
     
    def __str__(self):
        """Unicode representation of EspecialidadMedico."""
        return '{}'.format(self.descripcion)
    
    def save(self, *args, **kwargs):
        """Save method for Analisis_Radiografico."""
        self.descripcion = self.descripcion.lower().strip()
        return super(EspecialidadMedico, self).save(*args, **kwargs)
    
    
#vacuna
class Vacuna(ModeloBase):
    descripcion = models.CharField("Vacuna", max_length=200 , unique=True)
     
    def __str__(self):
        """Unicode representation of EspecialidadMedico."""
        return '{}'.format(self.descripcion)
    
    def save(self, *args, **kwargs):
        """Save method for Analisis_Radiografico."""
        self.descripcion = self.descripcion.lower().strip()
        return super(Vacuna, self).save(*args, **kwargs)
  
#MEDICO
class Medico(ModeloBase):      
        
    usuario  = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name="Usuario",on_delete=models.PROTECT)
    especialidad = models.ForeignKey(EspecialidadMedico, verbose_name="Especialidad", on_delete=models.PROTECT)
    def __str__(self):
        """Unicode representation of Analisis_Radiografico."""
        return '{}'.format(self.usuario.get_full_name())
    
    class Meta:
        '''Meta doctor'''
        permissions = (
            ("see_view_report", "Can_view_report"),
        )
         
# PACIENTE
class Paciente(ModeloBase):
     usuario  = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name="Usuario",on_delete=models.PROTECT)
     direccion = models.CharField("Dirección", max_length=200,blank=True )
     es_vacunado = models.BooleanField(verbose_name="¿Está usted vacunado contra el covid?" )
     vacuna = models.ForeignKey(Vacuna, verbose_name="Tipo de Vacuna", on_delete=models.PROTECT,null=True,blank=True)
     Diagnostico = models.TextField(verbose_name="Diágnostico previo",null=True, blank=True)
     fec_nac = models.DateField(verbose_name='Fecha de Nacimiento',default=date.today)
     
     def __str__(self):
        """Unicode representation of Analisis_Radiografico."""
        return '{} CI: {}'.format(self.usuario.get_full_name(),self.usuario.cedula)
    
     def save(self, *args, **kwargs):
        """Save method for Analisis_Radiografico."""
        self.direccion = self.direccion.lower().strip()
        return super(Paciente, self).save(*args, **kwargs)

#MODELO MENU 
class Menu(ModeloBase):
    """Model definition for Menu."""
    titulo = models.CharField(verbose_name='Título',max_length=200)
    descripcion = models.CharField( verbose_name='Descripciòn',max_length=200)
    icono = models.ImageField(verbose_name="icono", upload_to='icon/')
    url = models.CharField(verbose_name='Url', max_length=200)
    grupo = models.ManyToManyField(Group, through='Menu_Groups', verbose_name='Grupos de usuario')
    activo = models.BooleanField(default=True)

    class Meta:
        """Meta definition for Menu."""
        verbose_name = 'Menu'
        verbose_name_plural = 'Menus'

    def __str__(self):
        """Unicode representation of Menu."""
        return '{}'.format(self.titulo)
    
    def save(self, *args, **kwargs):
        """Save method for Menu."""
        self.titulo = self.titulo.lower().strip()
        self.descripcion = self.descripcion.lower().strip()
        return super(Menu, self).save(*args, **kwargs)
    
@receiver(post_delete, sender=Menu)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem when corresponding `MediaFile` object
        is deleted."""
    ruta = settings.MEDIA_ROOT +"\\"+ str(instance.icono)
    if ruta:
        if os.path.isfile(ruta):
            os.remove(ruta)
                           
@receiver(pre_save, sender=Menu)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes old file from filesystem when corresponding `MediaFile`
        object is updated with new file."""
    if not instance.pk:
         return False
    if not instance.pk:
        return False

    try:
        old_file = Menu.objects.get(pk=instance.pk).icono
    except Menu.DoesNotExist:
        return False

    new_file = instance.icono
    if not old_file == new_file:
        ruta = settings.MEDIA_ROOT +"\\"+ str(old_file)
        if os.path.isfile(ruta):
            os.remove(ruta)
                
class Menu_Groups(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE)
    menu = models.ForeignKey(Menu,on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)

  
class Analisis_Radiografico(ModeloBase):
    paciente = models.ForeignKey(Paciente,on_delete=models.PROTECT, related_name="paciente_user")
    doctor = models.ForeignKey(Medico,on_delete=models.PROTECT, related_name="doctor_user")
    imagen = models.ImageField(verbose_name="Imagen de Rayos X", upload_to='muestra_covid/')
    result_analisis=models.BooleanField(verbose_name="Libre de Covid" )
    fecha = models.DateTimeField(verbose_name='Fecha de Registro', auto_now_add=True)
    descripcion = models.CharField(verbose_name='Descripcion', max_length=200)
    edad = models.IntegerField(verbose_name='Edad', null=True, blank=True)
    class Meta:
        """Meta definition for Analisis_Radiografico."""
        verbose_name = 'Analisis'
        verbose_name_plural = 'Analisis'
        
        permissions = (
            ("see_view_Analisis_paciente_only", "Can_view_Analisis_paciente_only"),
        )
         
   
    def __str__(self):
        """Unicode representation of Analisis_Radiografico."""
        return '{}'.format(self.paciente)
    
    def save(self, *args, **kwargs):
        """Save method for Analisis_Radiografico."""
        self.descripcion = self.descripcion.lower().strip()
        return super(Analisis_Radiografico, self).save(*args, **kwargs)

@receiver(post_delete, sender=Analisis_Radiografico)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem when corresponding `MediaFile` object
        is deleted."""
    ruta = settings.MEDIA_ROOT +"\\"+ str(instance.imagen)
    if ruta:
        if os.path.isfile(ruta):
            os.remove(ruta)
                           
@receiver(pre_save, sender=Analisis_Radiografico)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes old file from filesystem when corresponding `MediaFile`
        object is updated with new file."""
    if not instance.pk:
         return False
    if not instance.pk:
        return False

    try:
        old_file = Analisis_Radiografico.objects.get(pk=instance.pk).imagen
    except Menu.DoesNotExist:
        return False

    new_file = instance.imagen
    if not old_file == new_file:
        ruta = settings.MEDIA_ROOT +"\\"+ str(old_file)
        if os.path.isfile(ruta):
            os.remove(ruta)
  

app_covid/templates/menu/accesoModulo_editar.html
{% extends 'plantillaBase.html' %} {% block content %}
<div class="content">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">

            {% if form.errors %}

            <div class="alert alert-danger" role="alert">
                <h5 class="icon fas fa-bin">Error al guardar el registro!</h5>
                <ul>
                    {% for field in form %} {% for error in field.errors %}
                    <li>
                        {{error}}
                    </li>
                    {% endfor %} {% endfor %}
                </ul>

            </div>
            {% endif %}
        </div>

    </div>
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <form method="post" class="card-box" action="{% url 'menuAcceso_editar' object.id %}" enctype="multipart/form-data">
                <div class="row">

                    {% include "form_snippet.html" %}

                </div>
                <div class="m-t-20 text-center">
                    <a type="button" class="btn btn-danger submit-btn" href="{% url 'menuAcceso_listar' %}">Cancelar</a>
                    <button class="btn btn-primary submit-btn">Guardar Registro</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

app_covid/templates/menu/accesoModulo_listar.html
{% extends 'plantillaBase.html' %} {% block content %}
<div class="row ">
    <div class="col">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
</div>
<div class="mt-2">
    <form action="" method="GET">
        <div class="row filter-row">
            <div class="col-sm-6 col-md-3">
                <div class="form-group form-focus  focused">
                    <select class="form-control " name="grupo" id="id_grupo">

                        {% for dato in grupos %}
                        <option value="{{ dato.id}}">{{ dato.name }}</option>
                        {% endfor %}

                    </select>
                </div>
            </div>


            <div class="col-sm-6 col-md-3">
                <button type="submit" class="btn btn-primary btn-block"> Filtrar </button>
            </div>
        </div>

    </form>
</div>

<div class="row ">
    <div class="col-md-12">
        <div class="table-responsive">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-border table-striped custom-table  mb-0  no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                            <thead>
                                <tr>
                                    <th>Grupo</th>
                                    <th>Módulo</th>
                                    <th>Estado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for dato in object_list %}
                                <tr>
                                    <td>{{ dato.group }}</td>

                                    <td>{{ dato.menu }}</td>
                                    <td>
                                        {% if dato.activo == True%}
                                        <a class="badge " data-toggle="tooltip" data-placement="top" title="Activo"><span class="fa fa-check "></span></a> {% else %}
                                        <a class="badge " data-toggle="tooltip" data-placement="top" title="Activo"><span class="fa fa-times "></span></a> {% endif %}
                                    </td>




                                    <td class="text-right">
                                        <div class="dropdown dropdown-action">
                                            <a class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                {% if perms.covid.change_menu_groups %}
                                                <a class="dropdown-item" href="{% url 'menuAcceso_editar' dato.id%}"><i
                                                        class="fa fa-pencil m-r-5"></i> Cambiar Estado</a> {% endif %}

                                            </div>
                                        </div>
                                    </td>

                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>

        <div class="container-fluid">
            <!-- /paginador -->
            <ul class="pagination pagination-sm m-0 float-right">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center mt-2">

                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                        {% endif %} {% for i in page_obj.paginator.page_range %} {% if i == page_obj.number %}
                        <li class="page-item active">
                            <a class="page-link" href="#">{{ i }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                        {% endif %} {% endfor %} {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                        </li>
                        {% endif %}

                    </ul>
                </nav>
            </ul>
        </div>
    </div>
</div>





{% endblock %} {% block content_extra_js %}
<script>
    /** funcion para abrir el modal de eliminar */
    function abrirModalCambiarEstado(url) {

        $('#cambiarEstado').load(url, function() {
            $('#cambiarEstado').modal('show');
        })
    }
</script>

{% endblock content_extra_js %}

app_covid/templates/menu/menu_crear.html
{% extends 'plantillaBase.html' %} {% block content %}
<div class="content">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">

            {% if form.errors %}

            <div class="alert alert-danger" role="alert">
                <h5 class="icon fas fa-bin">Error al guardar el registro!</h5>
                <ul>
                    {% for field in form %} {% for error in field.errors %}
                    <li>
                        {{error}}
                    </li>
                    {% endfor %} {% endfor %}
                </ul>

            </div>
            {% endif %}
        </div>

    </div>
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <form method="post" class="card-box" enctype="multipart/form-data">
                <div class="row">

                    {% include "form_snippet.html" %}

                </div>
                <div class="m-t-20 text-center">
                    <a type="button" class="btn btn-danger submit-btn" href="{% url 'menu_listar' %}">Cancelar</a>
                    <button class="btn btn-primary submit-btn">Guardar Registro</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

app_covid/templates/menu/menu_editar.html
{% extends 'plantillaBase.html' %} {% block content %}
<div class="content">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">

            {% if form.errors %}

            <div class="alert alert-danger" role="alert">
                <h5 class="icon fas fa-bin">Error al guardar el registro!</h5>
                <ul>
                    {% for field in form %} {% for error in field.errors %}
                    <li>
                        {{error}}
                    </li>
                    {% endfor %} {% endfor %}
                </ul>

            </div>
            {% endif %}
        </div>

    </div>
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <form method="post" class="card-box" action="{% url 'menu_editar' object.id %}" enctype="multipart/form-data">
                <div class="row">

                    {% include "form_snippet.html" %}

                </div>
                <div class="m-t-20 text-center">
                    <a type="button" class="btn btn-danger submit-btn" href="{% url 'menu_listar' %}">Cancelar</a>
                    <button class="btn btn-primary submit-btn">Guardar Registro</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

app_covid/templates/menu/menu_listar.html
{% extends 'plantillaBase.html' %} {% block content %}
<div class="row">
    <div class="col">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
</div>

<div class="mt-2">
    <form action="" method="GET">
        <div class="row filter-row">
            <div class="col-sm-6 col-md-3">
                <div class="form-group form-focus select-focus focused">
                    <input type="text" name="buscar" id="id_buscar" class="form-control float-right" placeholder="Buscar">
                </div>
            </div>


            <div class="col-sm-6 col-md-3">
                <button type="submit" class="btn btn-primary btn-block"> Filtrar </button>
            </div>
        </div>

    </form>
</div>

<div class="row ">

    <div class="col-sm-12 col-12 text-right m-b-20">
        {% if perms.covid.add_menu %}
        <a href="{% url 'menu_crear'%}" class="btn btn btn-primary btn-rounded float-right"><i class="fa fa-plus"></i>
            Añadir</a> {% endif %}

    </div>

</div>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">

                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-border table-striped custom-table  mb-0  no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Descripción</th>
                                    <th>Icono</th>
                                    <th>Url</th>
                                    <th>Grupos</th>
                                    <th>Activo</th>
                                    <th>Principal</th>

                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for dato in object_list %}
                                <tr>
                                    <td>{{ dato.titulo }}</td>

                                    <td>{{ dato.descripcion }}</td>

                                    {% if dato.icono %}
                                    <td><img src="{{dato.icono.url}}" class="img-thumbnail" width="40px"></td>{% else %}
                                    <td><a href="#">No tiene icono</a> </td> {% endif %}

                                    <td>{{ dato.url }}</td>
                                    <td>
                                        <ul>
                                            {% for dato in dato.grupo.all %}
                                            <li class="badge badge-pill badge-info">{{ dato }}</li>
                                            {% endfor %}
                                        </ul>
                                    </td>

                                    <td>
                                        {% if dato.activo == True%}
                                        <a class="badge " data-toggle="tooltip" data-placement="top" title="Activo"><span class="fa fa-check "></span></a> {% else %}
                                        <a class="badge " data-toggle="tooltip" data-placement="top" title="Activo"><span class="fa fa-times "></span></a> {% endif %}
                                    </td>
                                    <td>
                                        {% if dato.es_modulo_principal == True %}
                                        <a class="badge " data-toggle="tooltip" data-placement="top" title="Es principal"><span class="fa fa-check "></span></a> {% else %}
                                        <a class="badge" data-toggle="tooltip" data-placement="top" title="Es principal"><span class="fa fa-times "></span></a> {% endif %}
                                    </td>



                                    <td class="text-right">
                                        <div class="dropdown dropdown-action">
                                            <a class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                {% if perms.covid.change_menu %}
                                                <a class="dropdown-item" href="{% url 'menu_editar' dato.id%}"><i
                                                        class="fa fa-pencil m-r-5"></i> Editar</a> {% endif %} {% if perms.covid.delete_menu %}
                                                <a class="dropdown-item" onclick="abrirModalEliminar('{% url 'menu_eliminar' dato.id%}')"><i
                                                        class="fa fa-trash-o  m-r-5"></i>Eliminar</a>{% endif %} {% if perms.covid.view_menu %}
                                                <a class="dropdown-item" onclick="abrirModalDetalle('{% url 'menu_detalle' dato.id%}')"><i
                                                        class="fa fa-eye  m-r-5"></i>Ver</a>{% endif %}

                                            </div>
                                        </div>
                                    </td>

                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>


                </div>

            </div>
        </div>

        <div class="container-fluid">
            <!-- /paginador -->
            <ul class="pagination pagination-sm m-0 float-right">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center mt-2">

                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                        {% endif %} {% for i in page_obj.paginator.page_range %} {% if i == page_obj.number %}
                        <li class="page-item active">
                            <a class="page-link" href="#">{{ i }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                        {% endif %} {% endfor %} {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                        </li>
                        {% endif %}

                    </ul>
                </nav>
            </ul>
        </div>
    </div>
</div>




<!-- Modal Eliminar -->
<div class="modal fade" id="eliminar" role="dialog">

</div>

<!-- Large modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="detalle" aria-hidden="true">

</div>


{% endblock %} {% block content_extra_js %}
<script>
    /** funcion para abrir el modal de eliminar */
    function abrirModalEliminar(url) {

        $('#eliminar').load(url, function() {
            $('#eliminar').modal('show');
        })
    }

    /** funcion para abrir el modal de eliminar */
    function abrirModalDetalle(url) {

        $('#detalle').load(url, function() {
            $('#detalle').modal('show');
        })
    }
</script>


{% endblock content_extra_js %}